#!/bin/bash

## Description: import given test data into ddev (database and configurations)
## Usage: initialize
## Example: "ddev initialize"

if ! command -v "git-lfs" &> /dev/null
then
    echo "COMMAND "git lfs" could not be found"
    echo "Please install git-lfs support, see: https://git-lfs.github.com/"
    exit
fi

echo "Fetching database"
git lfs pull

echo "Symlink configuration"
mkdir -p .build/config/sites/main
ln -snf ../../../.project/config/typo3/config.yaml config/sites/main/config.yaml
mkdir -p .build/config/system
ln -snf ../../.project/config/typo3/settings.php config/system/settings.php
ln -snf ../../.project/config/typo3/additional.php config/system.additional.php

echo "Importing database"
ddev import-db --file=.project/data/db.sql.gz

echo "Run 'composer install'"
ddev composer install
ddev describe

echo "Thanks for supporting 'EXT:powermail_cleaner"
