services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  In2code\PowermailCleaner\:
    resource: '../Classes/*'
    exclude:
      - '../Classes/Domain/Model/*'

  In2code\PowermailCleaner\Command\CleanupCommand:
    tags:
      - name: console.command
        command: 'powermail_cleaner:cleanup'
        description: 'Cleans up powermail mails based on on the saved deletion date'

  In2code\PowermailCleaner\EventListener\FlexFormParsingModifyEventListener:
    tags:
      - name: 'event.listener'
        identifier: 'powermailcleaner:modify-data-structure'
        after: 'powermail-modify-data-structure'

  In2code\PowermailCleaner\EventListener\BackendPageModulePreviewContentEventListener:
    tags:
      - name: 'event.listener'
        identifier: 'powermailcleaner:page-layout-preview'

  In2code\PowermailCleaner\EventListener\FormControllerCreateActionBeforeRenderViewEventListener:
    tags:
      - name: 'event.listener'
        identifier: 'powermailcleaner:powermail-mail-add-fields'
